-- MySQL Script generated by MySQL Workbench
-- Wed Dec 29 14:32:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`boots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`boots` ;

CREATE TABLE IF NOT EXISTS `mydb`.`boots` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cost` INT NOT NULL,
  `hardness` FLOAT NOT NULL,
  `weight` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chestplate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chestplate` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chestplate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cost` INT NOT NULL,
  `hardness` FLOAT NOT NULL,
  `weight` FLOAT NOT NULL,
  `max_additional_equipment` INT NOT NULL,
  `heart_crystal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`helmet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`helmet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`helmet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cost` INT NOT NULL,
  `hardness` FLOAT NOT NULL,
  `weight` FLOAT NOT NULL,
  `helmet_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leggins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`leggins` ;

CREATE TABLE IF NOT EXISTS `mydb`.`leggins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cost` INT NOT NULL,
  `hardness` FLOAT NOT NULL,
  `weight` FLOAT NOT NULL,
  `pocket_quantity` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`armor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`armor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`armor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `boots_id` INT NOT NULL,
  `chestplate_id` INT NOT NULL,
  `helmet_id` INT NOT NULL,
  `leggins_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_armor_boots_idx` (`boots_id` ASC) VISIBLE,
  INDEX `fk_armor_chestplate1_idx` (`chestplate_id` ASC) VISIBLE,
  INDEX `fk_armor_helmet1_idx` (`helmet_id` ASC) VISIBLE,
  INDEX `fk_armor_leggins1_idx` (`leggins_id` ASC) VISIBLE,
  CONSTRAINT `fk_armor_boots`
    FOREIGN KEY (`boots_id`)
    REFERENCES `mydb`.`boots` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_armor_chestplate1`
    FOREIGN KEY (`chestplate_id`)
    REFERENCES `mydb`.`chestplate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_armor_helmet1`
    FOREIGN KEY (`helmet_id`)
    REFERENCES `mydb`.`helmet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_armor_leggins1`
    FOREIGN KEY (`leggins_id`)
    REFERENCES `mydb`.`leggins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`knight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`knight` ;

CREATE TABLE IF NOT EXISTS `mydb`.`knight` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `service_years` INT NOT NULL,
  `armor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_knight_armor1_idx` (`armor_id` ASC) VISIBLE,
  CONSTRAINT `fk_knight_armor1`
    FOREIGN KEY (`armor_id`)
    REFERENCES `mydb`.`armor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
